services:
  postgres:
    image: postgres:15
    container_name: expense-db
    environment:
      POSTGRES_DB: expense_manager
      POSTGRES_USER: survidia
      POSTGRES_PASSWORD: survidia123
    ports:
      - "5432:5432"
    volumes:
      - expense_data:/var/lib/postgresql/data

volumes:
  expense_data: