server:
  port: 8080

spring:
  application:
    name: Expense Manager

  datasource:
    url: jdbc:postgresql://localhost:5432/expense_manager
    username: survidia
    password: survidia123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: expense_manager